input {
  file {
    path => "E:/Nouveau dossier/Install/Dossier_Xampp/htdocs/KMS_Audit_ELK/elk/logs-kms.json"
    start_position => "beginning"
    sincedb_path => "NUL"
    codec => "json"
  }
}

filter {
  mutate {
    add_field => {
      "application" => "KMS Audit ELK"
      "type_systeme" => "plateforme_kms"
    }
  }

  date {
    match => [ "horodatage", "ISO8601" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "kms-audit-logs"
  }

  stdout {
    codec => rubydebug
  }
}